version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
      - pip install flake8 bandit

  build:
    commands:
      - python manage.py migrate
      - python manage.py test
      - flake8 .
      - bandit -r .

artifacts:
  files:
    - '**/*'